package com.acme.model;

import lombok.Data;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.properties.ConfigurationProperties;

@Data
@ConfigurationProperties("autogenerated.rootnode3")
public class RootNode3 {
    /**
     * Charlie fresh comment
     */
    @Value("${autogenerated.rootnode3:other}")
    private String charlie;
    /**
     * Delta comment
     */
    private int delta;
    /**
     * Top level enum comment
     */
    private TopLevelEnum topLevelEnum;
}
